# Generated by Django 4.2.2 on 2023-07-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('author', models.CharField(max_length=70)),
                ('pages_number', models.IntegerField()),
                ('pub_year', models.IntegerField()),
                ('pub_by', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=250)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fav_book',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_books', through='books.UserBookFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
