# Generated by Django 4.2.2 on 2023-07-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='users',
            new_name='user',
        ),
    ]
