# Generated by Django 4.2.2 on 2023-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_users_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='users',
        ),
    ]
