# Generated by Django 4.2.2 on 2023-07-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_book_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='UserBookFavorite',
        ),
    ]
