# Generated by Django 4.2.2 on 2023-07-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_book_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='UserBookFavorite',
        ),
    ]
