# Generated by Django 4.2.2 on 2023-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_favorites_delete_userbookfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
