# Generated by Django 4.2.2 on 2023-07-04 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 23, 1, 24, 742210, tzinfo=datetime.timezone.utc)),
        ),
    ]
