# Generated by Django 4.2.2 on 2023-07-04 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 23, 5, 37, 129034, tzinfo=datetime.timezone.utc)),
        ),
    ]
