# Generated by Django 4.2.2 on 2023-07-05 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 13, 43, 58, 840564, tzinfo=datetime.timezone.utc)),
        ),
    ]
