# Generated by Django 4.2.2 on 2023-07-06 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_due_date_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 12, 32, 5, 882652, tzinfo=datetime.timezone.utc)),
        ),
    ]
