# Generated by Django 4.2.2 on 2023-07-06 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 12, 34, 34, 585046, tzinfo=datetime.timezone.utc)),
        ),
    ]
