# Generated by Django 4.2.2 on 2023-07-06 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 14, 29, 44, 676283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
