# Generated by Django 4.2.2 on 2023-07-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
        ('loans', '0011_alter_loan_due_date_alter_loan_loan_date_and_more'),
    ]

    operations = [
    ]
