# Generated by Django 4.2.2 on 2023-07-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_merge_20230706_1448'),
        ('loans', '0012_merge_20230707_1003'),
    ]

    operations = [
    ]
