# Generated by Django 4.2.2 on 2023-07-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='number_of_copies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
